Updated to AIR28 and Android API v25 + including Android-x86 platform and test build script for Android Emulator
But needs review as it crashes with:

java.io.FileNotFoundException: Corrupt XML binary file